import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  mapContainer: {
    flex: 1,
    position: 'relative',
  },
  map: {
    width: width,
    height: height,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  loadingText: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 10,
    fontWeight: '600',
  },
  centerMarkerContainer: {
    position: 'absolute',
    left: '50%',
    top: '35%', // Positioned exactly in the center of the open map area (above bottom sheet)
    marginLeft: -20,
    marginTop: -40,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  pinIcon: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  pinShadow: {
    position: 'absolute',
    bottom: -2,
    width: 8,
    height: 4,
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 4,
  },
  menuBtn: {
    position: 'absolute',
    left: 16,
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 6,
    zIndex: 5,
  },
  locateBtn: {
    position: 'absolute',
    right: 16,
    bottom: 460, // Above the bottom sheet on all screen sizes
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 6,
    zIndex: 5,
  },
  activeTaskBanner: {
    position: 'absolute',
    left: 80,
    right: 16,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 6,
    zIndex: 5,
  },
  bannerIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981',
    marginRight: 10,
  },
  bannerText: {
    fontSize: 13,
    color: '#1F2937',
    flex: 1,
  },
  boldText: {
    fontWeight: '700',
  },
  bottomSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 16,
    paddingTop: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 20,
    zIndex: 4,
  },
  sheetHandle: {
    width: 40,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#E5E7EB',
    alignSelf: 'center',
    marginBottom: 10,
  },
  sheetTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 10,
  },
  categoriesScroll: {
    paddingTop: 6, // Adds top headroom so scaled-up selected categories are not clipped
    paddingBottom: 10,
    gap: 8,
  },
  categoryCard: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 64,
    marginRight: 6,
  },
  categoryCardSelected: {
    transform: [{ scale: 1.05 }],
  },
  categoryIconCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  categoryLabel: {
    fontSize: 9,
    fontWeight: '600',
    color: '#4B5563',
    textAlign: 'center',
  },
  categoryLabelSelected: {
    color: '#10B981',
    fontWeight: '800',
  },
  inputContainer: {
    marginTop: 10,
    gap: 10,
  },
  addressPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    borderRadius: 12,
    height: 42,
    paddingHorizontal: 12,
  },
  addressText: {
    fontSize: 13,
    color: '#374151',
    flex: 1,
  },
  formRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  budgetInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    borderRadius: 12,
    height: 42,
    paddingHorizontal: 8,
    flex: 0.35,
  },
  currencyPrefix: {
    fontSize: 13,
    fontWeight: '700',
    color: '#111827',
    marginRight: 4,
  },
  budgetInput: {
    flex: 1,
    fontSize: 13,
    color: '#111827',
    fontWeight: '600',
  },
  paymentSelectorContainer: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    height: 42,
    padding: 3,
    flex: 0.63,
    gap: 6,
  },
  paymentBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    paddingHorizontal: 4,
  },
  paymentBtnSelected: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  paymentBtnLabel: {
    fontSize: 9,
    fontWeight: '600',
    color: '#6B7280',
    marginLeft: 3,
  },
  paymentLabelSelected: {
    color: '#10B981',
    fontWeight: '800',
  },
  descriptionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 42,
  },
  descriptionInput: {
    flex: 1,
    fontSize: 13,
    color: '#111827',
    padding: 0,
    textAlignVertical: 'center',
  },
  actionButton: {
    backgroundColor: '#082C18',
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 3,
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 15,
  },
  sheetHandleContainer: {
    width: '100%',
    paddingVertical: 8,
    alignItems: 'center',
  },
  collapsedHeader: {
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 8,
    width: '100%',
  },
  collapsedAddressText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 2,
    paddingHorizontal: 20,
    textAlign: 'center',
  },
  collapsedSubText: {
    fontSize: 10,
    color: '#10B981',
    fontWeight: '700',
  },
  locateBtnPressable: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sheetSearchContainer: {
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    marginVertical: 4,
  },
  inputSectionTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#4B5563',
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  sheetSearchInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    height: 40,
  },
  sheetSearchInput: {
    flex: 1,
    height: '100%',
    fontSize: 13,
    color: '#111827',
    paddingHorizontal: 8,
  },
  sheetSearchResultsList: {
    marginTop: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
  },
  sheetSearchResultCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  sheetSearchResultIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FEE2E2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  sheetSearchResultNameText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1F2937',
  },
  sheetSearchResultAddrText: {
    fontSize: 11,
    color: '#6B7280',
    marginTop: 1,
  },
  noResultsText: {
    fontSize: 12,
    color: '#9CA3AF',
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },
  sheetCurrentAddressBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    paddingHorizontal: 4,
  },
  sheetCurrentAddressText: {
    fontSize: 12,
    color: '#4B5563',
    flex: 1,
    fontWeight: '500',
  },
  categoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 6,
    marginVertical: 4,
  },
  categoryGridCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    borderRadius: 12,
    width: '45.5%',
    marginHorizontal: 6,
    paddingVertical: 6,
    paddingHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 1,
    elevation: 1,
  },
  categoryGridCardSelected: {
    borderColor: '#10B981',
    backgroundColor: '#ECFDF5',
    transform: [{ scale: 1.02 }],
  },
  categoryGridLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#374151',
    marginLeft: 8,
    flex: 1,
  },
  categoryGridLabelSelected: {
    color: '#065F46',
    fontWeight: '700',
  },
  sheetLocFormContainer: {
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    marginVertical: 4,
    gap: 8,
  },
  sheetLocFormRow: {
    flexDirection: 'row',
    gap: 8,
  },
  sheetLocInputWrapper: {
    flexDirection: 'column',
    gap: 4,
  },
  sheetLocFieldLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#4B5563',
    textTransform: 'uppercase',
  },
  sheetLocInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 10,
    height: 38,
    paddingHorizontal: 10,
    fontSize: 12,
    color: '#111827',
  },
  sheetLocSubmitBtn: {
    backgroundColor: '#10B981',
    height: 38,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 4,
  },
  sheetLocSubmitBtnText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 13,
  },
  categoriesGridScrollContainer: {
    height: 135,
    width: '100%',
    marginVertical: 4,
  },
  sheetHeaderWithAction: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  seeAllBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 12,
    backgroundColor: '#ECFDF5',
  },
  seeAllBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#10B981',
  },
  attachmentsContainer: {
    marginTop: 10,
    marginBottom: 6,
  },
  attachmentsTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#4B5563',
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  attachmentsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  attachmentCard: {
    width: 60,
    height: 60,
    borderRadius: 10,
    position: 'relative',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  attachmentImage: {
    width: '100%',
    height: '100%',
  },
  uploadOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadText: {
    fontSize: 8,
    fontWeight: '700',
    color: '#FFFFFF',
    marginTop: 2,
  },
  removeBtn: {
    position: 'absolute',
    top: 2,
    right: 2,
    zIndex: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
  },
  addAttachmentBtn: {
    width: 60,
    height: 60,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#9CA3AF',
    backgroundColor: '#F9FAFB',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 2,
  },
  addAttachmentText: {
    fontSize: 8,
    fontWeight: '600',
    color: '#6B7280',
  },
  skeletonCard: {
    width: 64,
    height: 64,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    marginRight: 6,
  },
  skeletonGridCard: {
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    width: '45.5%',
    height: 46,
    marginHorizontal: 6,
    marginVertical: 4,
  },
  paymentBtnSkeleton: {
    flex: 1,
    height: 36,
    backgroundColor: '#E5E7EB',
    borderRadius: 9,
  },
  noInternetBanner: {
    position: 'absolute',
    left: '10%',
    right: '10%',
    alignSelf: 'center',
    backgroundColor: '#EF4444',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 6,
    zIndex: 10,
  },
  noInternetText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  smartRetryCard: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FCA5A5',
    borderRadius: 14,
    padding: 14,
    marginHorizontal: 16,
    marginVertical: 10,
    gap: 8,
  },
  smartRetryHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  smartRetryTitle: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#991B1B',
    flex: 1,
  },
  smartRetrySubText: {
    fontSize: 12,
    color: '#7F1D1D',
    lineHeight: 16,
  },
  smartRetryBtn: {
    backgroundColor: '#DC2626',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 10,
    marginTop: 4,
  },
  smartRetryBtnDisabled: {
    backgroundColor: '#F87171',
  },
  smartRetryBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
});
