import { StyleSheet, Dimensions, Platform } from 'react-native';

const { height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0F5C43',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 8,
  },
  headerBackBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerProgressContainer: {
    flexDirection: 'row',
    flex: 1,
    height: 5,
    gap: 8,
    marginLeft: 24,
  },
  progressSegmentTrack: {
    flex: 1,
    height: 5,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressSegmentFill: {
    height: '100%',
    backgroundColor: '#10B981',
    borderRadius: 2,
  },
  cardWrapper: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 8,
  },
  heroCard: {
    borderRadius: 32,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.15,
    shadowRadius: 30,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  innerCard: {
    justifyContent: 'center',
  },
  illustrationContainer: {
    height: height * 0.33,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 24,
    backgroundColor: 'rgba(15, 92, 67, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(15, 92, 67, 0.05)',
  },
  glowCircle: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
  },
  houseOutline: {
    position: 'absolute',
    opacity: 0.9,
  },
  pakBadge: {
    position: 'absolute',
    top: 14,
    backgroundColor: '#FFFFFF',
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(15, 92, 67, 0.08)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  pakBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0F5C43',
  },
  providerCard: {
    position: 'absolute',
    bottom: 24,
    left: 20,
    right: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(15, 92, 67, 0.08)',
    shadowColor: '#0F5C43',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  avatarContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#E6F4F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  providerDetails: {
    marginLeft: 10,
    flex: 1,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  providerName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1F2937',
  },
  providerType: {
    fontSize: 11,
    color: '#6B7280',
    fontWeight: '500',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    paddingTop: 6,
  },
  ratingText: {
    fontSize: 10,
    color: '#4B5563',
    fontWeight: '600',
    marginLeft: 4,
  },
  floatingBadge: {
    position: 'absolute',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: 'rgba(15, 92, 67, 0.08)',
  },
  badgeHammer: {
    top: 55,
    left: 24,
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  badgeWrench: {
    top: 90,
    right: 28,
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  radarRing: {
    position: 'absolute',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.1)',
    borderStyle: 'dashed',
  },
  radarRingLarge: {
    width: 250,
    height: 250,
  },
  radarRingMedium: {
    width: 170,
    height: 170,
  },
  radarRingSmall: {
    width: 90,
    height: 90,
  },
  glowingCenter: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
  },
  centerPinWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ translateY: -10 }],
  },
  pinShadow: {
    width: 12,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(0, 0, 0, 0.15)',
    marginTop: -2,
  },
  locationBadge: {
    position: 'absolute',
    top: 14,
    backgroundColor: '#FFFFFF',
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(15, 92, 67, 0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  locationBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0F5C43',
  },
  nearbyWorker: {
    position: 'absolute',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 2,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  avatarMini: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#4B5563',
  },
  onlineDot: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  workerPos1: {
    top: 50,
    left: 45,
  },
  workerPos2: {
    bottom: 120,
    right: 50,
  },
  workerPos3: {
    top: 80,
    right: 70,
  },
  confirmationCard: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    right: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.15)',
    shadowColor: '#0F5C43',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  checkWrapper: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#10B981',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
  },
  confirmationTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1F2937',
  },
  confirmationDetails: {
    fontSize: 10,
    color: '#6B7280',
    fontWeight: '500',
    marginLeft: 24,
    marginBottom: 4,
  },
  starsRow: {
    flexDirection: 'row',
    marginLeft: 24,
    gap: 2,
  },
  requestCard: {
    position: 'absolute',
    top: 14,
    left: 16,
    right: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(15, 92, 67, 0.08)',
    shadowColor: '#0F5C43',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  requestHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  alertPulse: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EF4444',
    marginRight: 6,
  },
  requestLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: '#EF4444',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  requestTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 2,
  },
  requestLocation: {
    fontSize: 10,
    color: '#6B7280',
    fontWeight: '500',
    marginBottom: 10,
  },
  acceptMockBtn: {
    backgroundColor: '#10B981',
    borderRadius: 10,
    paddingVertical: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  acceptMockBtnText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  walletCard: {
    position: 'absolute',
    bottom: 14,
    left: 16,
    width: 140,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(15, 92, 67, 0.08)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  walletHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  walletLabel: {
    fontSize: 8,
    fontWeight: '700',
    color: '#6B7280',
    marginLeft: 3,
    textTransform: 'uppercase',
  },
  walletAmount: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F5C43',
    marginBottom: 6,
  },
  sparklineRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 26,
    gap: 3,
  },
  sparklineBar: {
    flex: 1,
    backgroundColor: '#E6F4F0',
    borderRadius: 2,
  },
  reviewBubble: {
    position: 'absolute',
    bottom: 48,
    right: 16,
    width: 140,
    backgroundColor: '#0F5C43',
    borderRadius: 14,
    borderBottomRightRadius: 2,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  reviewText: {
    fontSize: 9,
    fontWeight: '600',
    color: '#FFFFFF',
    lineHeight: 12,
  },
  bubbleTail: {
    position: 'absolute',
    right: 0,
    bottom: -6,
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderLeftWidth: 6,
    borderRightWidth: 0,
    borderTopWidth: 6,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#0F5C43',
  },
  badgeSuccess: {
    position: 'absolute',
    bottom: 14,
    right: 16,
    backgroundColor: '#FFFFFF',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FEE2E2',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  badgeSuccessText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#D97706',
  },
  textContainer: {
    marginTop: 20,
    paddingHorizontal: 4,
  },
  slideTitle: {
    color: '#0F5C43',
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 34,
    marginBottom: 8,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },
  slideSubtitle: {
    color: '#4B5563',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '400',
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingBottom: Platform.OS === 'ios' ? 12 : 24,
    paddingTop: 12,
  },
  bottomSkipBtn: {
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomSkipText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  bottomSkipPlaceholder: {
    width: 68,
  },
  nextBtnWrapper: {
    flex: 1,
    marginLeft: 16,
    height: 52,
    borderRadius: 26,
    overflow: 'hidden',
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  nextBtnGradient: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  nextBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
});
